-- 이 줄 끝까지 주석
/* 영역 주석 */

-- hr 사용자 계정 복구 (활성화)
ALTER USER HR ACCOUNT UNLOCK;
ALTER USER HR IDENTIFIED BY "HR"; -- 비밀번호 변경

-- scott 계정 만들기
CREATE USER SCOTT IDENTIFIED BY TIGER; -- 계정 생성
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO SCOTT; -- 권한부여
ALTER USER SCOTT DEFAULT TABLESPACE USERS;  -- 데이터파일 저장 위치
ALTER USER SCOTT TEMPORARY TABLESPACE TEMP;

-- kdtda2 계정 만들기
CREATE USER kdtda2 IDENTIFIED BY "kdtda2";
GRANT CONNECT, RESOURCE TO kdtda2;
